"""empty message

Revision ID: 22446c128767
Revises: d73474ef7b6b
Create Date: 2025-05-21 08:56:55.750195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22446c128767'
down_revision = 'd73474ef7b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
